# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d060e2d61a6ae06cdb5f21a1db7b9a6661e118dab884227d4cf7d7b55a84023d43de964381b0bad755ac6bc81de779f0d15f12498c219fc992b2c4c103c7089b

test:
  secret_key_base: 89af31c7a64841f642f15593c1cbc70ff2d3b4cd6acff96eb246e3d671e206c6cae8d8cf701b4f546efc240f0ecf158287a9342a3a87faa97ca755612c3630cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
